import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "../globals.css";
import "react-toastify/dist/ReactToastify.css";
import PageTransitions from "@/components/ul/PageTransitions";
import Header from "@/components/ul/header";

const JetBrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-JetBrainsMono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${JetBrainsMono.variable} antialiased`}>
        <PageTransitions>
          <Header />
          {children}
        </PageTransitions>
      </body>
    </html>
  );
}
